// <auto-generated />
using System;
using MarionGI.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarionGI.Persistence.Migrations
{
    [DbContext(typeof(MarionDbContext))]
    [Migration("20260810160512_AjouterChamUtilisateurEnregistreurIDpPaiement")]
    partial class AjouterChamUtilisateurEnregistreurIDpPaiement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarionGI.Domain.Entities.Bien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<decimal>("Loyer")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Photos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProprietaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Quartier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<decimal>("Superficie")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProprietaireId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Biens");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Contrat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocataireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MontantCaution")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantLoyer")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BienId");

                    b.HasIndex("LocataireId");

                    b.ToTable("Contrats");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.DemandeVisite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateSouhaitee")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("NomProspect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("TelephoneProspect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("BienId");

                    b.ToTable("DemandesVisite");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.JournalAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntiteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("JournauxAudit");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<bool>("Lu")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Paiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContratId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("EnregistreParUtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<int>("ModePaiement")
                        .HasColumnType("int");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroQuittance")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReferenceTransactionOperateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatutTransaction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContratId");

                    b.HasIndex("NumeroQuittance")
                        .IsUnique();

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<bool>("EstRevoque")
                        .HasColumnType("bit");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("OtpExpiration")
                        .HasColumnType("datetime");

                    b.Property<string>("OtpSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<bool>("Statut")
                        .HasColumnType("bit");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TelephoneVerifie")
                        .HasColumnType("bit");

                    b.Property<int>("TentativesConnexionEchouees")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerrouilleJusquA")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telephone")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Bien", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.Utilisateur", "Proprietaire")
                        .WithMany("BiensProprietaire")
                        .HasForeignKey("ProprietaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proprietaire");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Contrat", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.Bien", "Bien")
                        .WithMany("Contrats")
                        .HasForeignKey("BienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarionGI.Domain.Entities.Utilisateur", "Locataire")
                        .WithMany("ContratsLocataire")
                        .HasForeignKey("LocataireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bien");

                    b.Navigation("Locataire");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.DemandeVisite", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.Utilisateur", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MarionGI.Domain.Entities.Bien", "Bien")
                        .WithMany("DemandesVisite")
                        .HasForeignKey("BienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Bien");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Paiement", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.Contrat", "Contrat")
                        .WithMany("Paiements")
                        .HasForeignKey("ContratId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrat");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Bien", b =>
                {
                    b.Navigation("Contrats");

                    b.Navigation("DemandesVisite");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Contrat", b =>
                {
                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("BiensProprietaire");

                    b.Navigation("ContratsLocataire");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
