// <auto-generated />
using System;
using MarionGI.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarionGI.Persistence.Migrations
{
    [DbContext(typeof(MarionDbContext))]
    partial class MarionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarionGI.Domain.Entities.BienImmobilier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Photos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quartier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Superficie")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SocieteId", "Nom")
                        .IsUnique()
                        .HasFilter("[EstSupprime] = 0");

                    b.HasIndex("SocieteId", "Reference")
                        .IsUnique()
                        .HasFilter("[EstSupprime] = 0");

                    b.ToTable("BiensImmobiliers");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Contrat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<int>("DelaiJoursTolerance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<int>("FrequencePaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("LocataireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MontantCaution")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantLoyer")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<Guid>("UniteLocativeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocataireId");

                    b.HasIndex("UniteLocativeId");

                    b.ToTable("Contrats");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.DemandeVisite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateSouhaitee")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("NomProspect")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("TelephoneProspect")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UniteLocativeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("UniteLocativeId");

                    b.ToTable("DemandesVisite");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.JournalAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntiteId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("JournauxAudit");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<bool>("Lu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Paiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContratId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("EnregistreParUtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<int>("ModePaiement")
                        .HasColumnType("int");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroQuittance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceTransactionOperateur")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StatutTransaction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContratId");

                    b.HasIndex("NumeroQuittance")
                        .IsUnique();

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<bool>("EstRevoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UtilisateurId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Societe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Adresse")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CodePostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroEntreprise")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Societes");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.UniteLocative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BienImmobilierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<decimal>("Loyer")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Photos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<decimal>("Superficie")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BienImmobilierId", "Reference")
                        .IsUnique();

                    b.ToTable("UnitesLocatives");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSuppression")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("OtpExpiration")
                        .HasColumnType("datetime");

                    b.Property<string>("OtpSecret")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Statut")
                        .HasColumnType("bit");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("TelephoneVerifie")
                        .HasColumnType("bit");

                    b.Property<int>("TentativesConnexionEchouees")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerrouilleJusquA")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("SocieteId", "Email")
                        .IsUnique();

                    b.HasIndex("SocieteId", "Telephone")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.BienImmobilier", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.Societe", "Societe")
                        .WithMany("BiensImmobiliers")
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Contrat", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.Utilisateur", "Locataire")
                        .WithMany("ContratsLocataire")
                        .HasForeignKey("LocataireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarionGI.Domain.Entities.UniteLocative", "UniteLocative")
                        .WithMany("Contrats")
                        .HasForeignKey("UniteLocativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Locataire");

                    b.Navigation("UniteLocative");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.DemandeVisite", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.Utilisateur", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MarionGI.Domain.Entities.UniteLocative", "UniteLocative")
                        .WithMany("DemandesVisite")
                        .HasForeignKey("UniteLocativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("UniteLocative");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Paiement", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.Contrat", "Contrat")
                        .WithMany("Paiements")
                        .HasForeignKey("ContratId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contrat");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.Utilisateur", "Utilisateur")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.UniteLocative", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.BienImmobilier", "BienImmobilier")
                        .WithMany("UnitesLocatives")
                        .HasForeignKey("BienImmobilierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BienImmobilier");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Utilisateur", b =>
                {
                    b.HasOne("MarionGI.Domain.Entities.Societe", "Societe")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.BienImmobilier", b =>
                {
                    b.Navigation("UnitesLocatives");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Contrat", b =>
                {
                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Societe", b =>
                {
                    b.Navigation("BiensImmobiliers");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.UniteLocative", b =>
                {
                    b.Navigation("Contrats");

                    b.Navigation("DemandesVisite");
                });

            modelBuilder.Entity("MarionGI.Domain.Entities.Utilisateur", b =>
                {
                    b.Navigation("ContratsLocataire");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
